version: "3.8"
services:
  db:
    image: mysql:8.0-oracle # to run on Apple M1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./scripts/Dockerfile
  #   command: node ./dist/app.js
  #   depends_on:
  #     - db

volumes:
  db_data:
